import type { Question, Quiz } from "@/lib/quizclash";

export type StarterQuiz = Quiz & {
  category: string;
  language: string;
  questions: Omit<Question, "id" | "quiz_id">[];
};

export const STARTER_QUIZZES: StarterQuiz[] = [
  {
    id: "starter-history-01",
    user_id: "system",
    title: "تاريخ عام",
    created_at: "2026-08-01T00:00:00.000Z",
    is_public: true,
    category: "history",
    language: "ar",
    questions: [
      {
        question_text: "في أي عام سقطت الإمبراطورية الرومانية الغربية؟",
        options: ["٣٧٦م", "٤٧٦م", "٥٧٦م", "٦٧٦م"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 0,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "متى اندلعت الثورة الفرنسية؟",
        options: ["١٧٧٦", "١٧٨٩", "١٨٠٤", "١٨١٥"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 1,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "من هو أول رئيس للولايات المتحدة الأمريكية؟",
        options: ["أبراهام لينكولن", "توماس جفرسون", "جورج واشنطن", "بنجامين فرانكلين"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 2,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "في أي معركة هُزم نابليون بونابرت بشكل نهائي؟",
        options: ["معركة الأهرام", "معركة واترلو", "معركة ترافلغار", "معركة أوسترليتز"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 3,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "متى انتهت الحرب العالمية الثانية؟",
        options: ["١٩٤٢", "١٩٤٤", "١٩٤٥", "١٩٤٨"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 4,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "في أي عام سقط جدار برلين؟",
        options: ["١٩٨٧", "١٩٨٩", "١٩٩١", "١٩٩٣"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 5,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "ما اسم الحرب التي استمرت أكثر من قرن بين إنجلترا وفرنسا؟",
        options: ["حرب الورود", "حرب المئة عام", "الحرب الأهلية الإنجليزية", "حرب الخلافة الإسبانية"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 6,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "من هو القائد الذي اكتشف القارة الأمريكية عام ١٤٩٢ بحسب السرد التقليدي؟",
        options: ["فاسكو دا جاما", "فرديناند ماجلان", "كريستوفر كولومبوس", "أميريغو فسبوتشي"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 7,
        image_url: null,
        question_type: "multi",
      },
    ],
  },
  {
    id: "starter-geography-02",
    user_id: "system",
    title: "جغرافيا عالمية",
    created_at: "2026-08-01T00:00:00.000Z",
    is_public: true,
    category: "geography",
    language: "ar",
    questions: [
      {
        question_text: "ما هو أكبر محيط في العالم من حيث المساحة؟",
        options: ["المحيط الأطلسي", "المحيط الهندي", "المحيط الهادئ", "المحيط المتجمد الشمالي"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 0,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "ما هي أكبر قارة في العالم من حيث المساحة؟",
        options: ["إفريقيا", "آسيا", "أمريكا الشمالية", "أوروبا"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 1,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "ما هو أعلى جبل في العالم؟",
        options: ["كي٢", "كليمنجارو", "إيفرست", "إلبروس"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 2,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "ما هي عاصمة أستراليا؟",
        options: ["سيدني", "ملبورن", "كانبيرا", "بيرث"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 3,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "ما هي أصغر دولة في العالم من حيث المساحة؟",
        options: ["موناكو", "سان مارينو", "الفاتيكان", "ليختنشتاين"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 4,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "كم عدد قارات العالم؟",
        options: ["خمس", "ست", "سبع", "ثمان"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 5,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "ما هو أطول نهر في العالم بحسب المقياس التقليدي؟",
        options: ["الأمازون", "النيل", "المسيسيبي", "اليانغتسي"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 6,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "أي دولة تُعد الأكثر سكاناً في العالم حالياً؟",
        options: ["الصين", "الهند", "الولايات المتحدة", "إندونيسيا"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 7,
        image_url: null,
        question_type: "multi",
      },
    ],
  },
  {
    id: "starter-science-03",
    user_id: "system",
    title: "علوم وفضاء",
    created_at: "2026-08-01T00:00:00.000Z",
    is_public: true,
    category: "science",
    language: "ar",
    questions: [
      {
        question_text: "ما هو أقرب كوكب إلى الشمس؟",
        options: ["الزهرة", "عطارد", "الأرض", "المريخ"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 0,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "من هو العالم الذي وضع نظرية النسبية؟",
        options: ["إسحاق نيوتن", "ألبرت أينشتاين", "نيلز بور", "ماكس بلانك"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 1,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "ما هو الغاز الأكثر وفرة في الغلاف الجوي للأرض؟",
        options: ["الأكسجين", "ثاني أكسيد الكربون", "النيتروجين", "الهيدروجين"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 2,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "كم عدد عظام جسم الإنسان البالغ؟",
        options: ["١٨٦", "١٩٦", "٢٠٦", "٢١٦"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 3,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "من هو أول إنسان مشى على سطح القمر؟",
        options: ["يوري غاغارين", "نيل أرمسترونغ", "باز ألدرين", "جون غلين"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 4,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "ما هي وحدة قياس شدة التيار الكهربائي؟",
        options: ["الفولت", "الأوم", "الأمبير", "الواط"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 5,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "ما اسم أقرب نجم إلى الأرض بعد الشمس؟",
        options: ["الشعرى اليمانية", "بروكسيما قنطورس", "الدبران", "قطب الشمال"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 6,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "كم تبلغ المسافة التقريبية بين الأرض والشمس؟",
        options: ["١٥٠ ألف كم", "١٥٠ مليون كم", "١٥ مليون كم", "١.٥ مليار كم"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 7,
        image_url: null,
        question_type: "multi",
      },
    ],
  },
  {
    id: "starter-arts-04",
    user_id: "system",
    title: "أدب وفنون",
    created_at: "2026-08-01T00:00:00.000Z",
    is_public: true,
    category: "arts",
    language: "ar",
    questions: [
      {
        question_text: "من مؤلف رواية \"مئة عام من العزلة\"؟",
        options: ["خورخي لويس بورخيس", "ماريو فارغاس يوسا", "غابرييل غارسيا ماركيز", "باولو كويلو"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 0,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "من هو الشاعر العربي الملقب بـ\"أمير الشعراء\"؟",
        options: ["المتنبي", "أحمد شوقي", "نزار قباني", "محمود درويش"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 1,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "من رسم لوحة الموناليزا؟",
        options: ["بيكاسو", "فان جوخ", "ليوناردو دافنشي", "مايكل أنجلو"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 2,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "من مؤلف \"الأمير الصغير\"؟",
        options: ["فيكتور هوغو", "ألبير كامو", "أنطوان دو سانت إكزوبيري", "جان بول سارتر"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 3,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "من كتب مسرحية \"هاملت\"؟",
        options: ["كريستوفر مارلو", "وليم شكسبير", "موليير", "هنريك إبسن"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 4,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "من هو الأديب العربي الوحيد الحائز على جائزة نوبل للآداب؟",
        options: ["طه حسين", "نجيب محفوظ", "توفيق الحكيم", "يوسف إدريس"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 5,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "من ألّف ملحمة \"الإلياذة\"؟",
        options: ["فيرجيل", "سوفوكليس", "هوميروس", "أرسطو"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 6,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "ما هي الحركة الفنية التي ينتمي إليها سلفادور دالي المعروف بلوحاته الغريبة؟",
        options: ["الانطباعية", "السريالية", "التكعيبية", "الواقعية"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 7,
        image_url: null,
        question_type: "multi",
      },
    ],
  },
  {
    id: "starter-sports-05",
    user_id: "system",
    title: "رياضة عالمية",
    created_at: "2026-08-01T00:00:00.000Z",
    is_public: true,
    category: "sports",
    language: "ar",
    questions: [
      {
        question_text: "كم عدد لاعبي فريق كرة القدم في الملعب لكل فريق؟",
        options: ["٩", "١٠", "١١", "١٢"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 0,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "أي منتخب فاز بأكبر عدد من كؤوس العالم لكرة القدم حتى الآن؟",
        options: ["ألمانيا", "الأرجنتين", "إيطاليا", "البرازيل"],
        correct_index: 3,
        time_limit_seconds: 30,
        order_index: 1,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "كل كم سنة تقام الألعاب الأولمبية الصيفية عادة؟",
        options: ["كل سنتين", "كل ٣ سنوات", "كل ٤ سنوات", "كل ٥ سنوات"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 2,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "في أي رياضة يُستخدم مضرب وكرة صغيرة بيضاء وحفر بعدد ١٨؟",
        options: ["التنس", "الغولف", "الكريكيت", "الاسكواش"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 3,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "أي دولة استضافت كأس العالم لكرة القدم عام ٢٠٢٢؟",
        options: ["الإمارات", "السعودية", "قطر", "الكويت"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 4,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "من هو لاعب كرة السلة الذي فاز بست بطولات إن بي إيه مع فريق شيكاغو بولز؟",
        options: ["ليبرون جيمس", "كوبي براينت", "مايكل جوردان", "ماجيك جونسون"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 5,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "كم شوطاً تتضمنه مباراة الملاكمة الاحترافية القياسية عادة؟",
        options: ["٨ أشواط", "١٠ أشواط", "١٢ شوطاً", "١٥ شوطاً"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 6,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "ما هي الرياضة التي تُعرف بـ\"الرياضة الملكية\" في بريطانيا وتشمل السباق على الخيل؟",
        options: ["البولو", "سباق الخيل", "الرماية", "التجديف"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 7,
        image_url: null,
        question_type: "multi",
      },
    ],
  },
  {
    id: "starter-islamic-06",
    user_id: "system",
    title: "تاريخ وحضارة عربية وإسلامية",
    created_at: "2026-08-01T00:00:00.000Z",
    is_public: true,
    category: "islamic_history",
    language: "ar",
    questions: [
      {
        question_text: "من هو أول الخلفاء الراشدين؟",
        options: ["عمر بن الخطاب", "أبو بكر الصديق", "عثمان بن عفان", "علي بن أبي طالب"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 0,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "في أي مدينة نزل الوحي على النبي محمد ﷺ لأول مرة؟",
        options: ["المدينة المنورة", "مكة المكرمة", "الطائف", "القدس"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 1,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "في أي دولة كان مقر الخلافة العباسية الرئيسي؟",
        options: ["مصر", "سوريا", "العراق", "تركيا"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 2,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "من هو القائد الذي يُنسب إليه فتح الأندلس؟",
        options: ["خالد بن الوليد", "عمرو بن العاص", "طارق بن زياد", "صلاح الدين الأيوبي"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 3,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "ما اسم المسجد الذي يُعد ثالث أقدس المساجد في الإسلام ويقع في القدس؟",
        options: ["المسجد الحرام", "المسجد النبوي", "المسجد الأقصى", "مسجد قبة الصخرة"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 4,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "في أي عام كانت الهجرة النبوية التي بدأ بها التقويم الهجري؟",
        options: ["٦١٠م", "٦٢٢م", "٦٣٢م", "٦٤٠م"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 5,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "من هو المؤرخ والمفكر العربي الذي يُعتبر رائداً في علم الاجتماع؟",
        options: ["ابن رشد", "ابن خلدون", "ابن سينا", "الفارابي"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 6,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "أين تقع أقدم جامعة في العالم ما زالت تعمل حتى اليوم بحسب اليونسكو؟",
        options: ["القاهرة، مصر", "بغداد، العراق", "فاس، المغرب", "دمشق، سوريا"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 7,
        image_url: null,
        question_type: "multi",
      },
    ],
  },
  {
    id: "starter-inventions-07",
    user_id: "system",
    title: "اختراعات واكتشافات",
    created_at: "2026-08-01T00:00:00.000Z",
    is_public: true,
    category: "inventions",
    language: "ar",
    questions: [
      {
        question_text: "من يُنسب إليه اختراع المصباح الكهربائي العملي؟",
        options: ["نيكولا تسلا", "توماس إديسون", "ألكسندر بيل", "مايكل فاراداي"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 0,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "من اخترع الهاتف؟",
        options: ["توماس إديسون", "غولييلمو ماركوني", "ألكسندر غراهام بيل", "نيكولا تسلا"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 1,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "من اخترع الطباعة بالحروف المتحركة في أوروبا؟",
        options: ["يوهانس غوتنبرغ", "ليوناردو دافنشي", "جيمس وات", "إسحاق نيوتن"],
        correct_index: 0,
        time_limit_seconds: 30,
        order_index: 2,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "من يُنسب إليه اختراع الشبكة العنكبوتية العالمية (WWW)؟",
        options: ["بيل غيتس", "ستيف جوبز", "تيم بيرنرز لي", "مارك زوكربيرغ"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 3,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "في أي حضارة اختُرع الورق لأول مرة؟",
        options: ["الحضارة المصرية", "الحضارة الصينية", "الحضارة اليونانية", "الحضارة الرومانية"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 4,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "من هما مخترعا أول طائرة تعمل بمحرك ونجحت بالتحليق؟",
        options: ["الأخوان رايت", "الأخوان لوميير", "توماس إديسون وهنري فورد", "جيمس وات وجورج ستيفنسون"],
        correct_index: 0,
        time_limit_seconds: 30,
        order_index: 5,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "من يُنسب إليه تطوير أول لقاح في التاريخ (ضد الجدري)؟",
        options: ["لويس باستور", "إدوارد جينر", "ألكسندر فليمنغ", "روبرت كوخ"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 6,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "من اخترع المحرك البخاري الذي ساهم في الثورة الصناعية؟",
        options: ["جيمس وات", "هنري فورد", "كارل بنز", "رودولف ديزل"],
        correct_index: 0,
        time_limit_seconds: 30,
        order_index: 7,
        image_url: null,
        question_type: "multi",
      },
    ],
  },
  {
    id: "starter-language-08",
    user_id: "system",
    title: "لغة وثقافة عامة",
    created_at: "2026-08-01T00:00:00.000Z",
    is_public: true,
    category: "language_culture",
    language: "ar",
    questions: [
      {
        question_text: "كم عدد حروف اللغة العربية؟",
        options: ["٢٦", "٢٧", "٢٨", "٢٩"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 0,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "من يُنسب إليه وضع أسس علم النحو العربي؟",
        options: ["الخليل بن أحمد الفراهيدي", "أبو الأسود الدؤلي", "سيبويه", "ابن مالك"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 1,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "كم عدد اللغات الرسمية المعتمدة في الأمم المتحدة؟",
        options: ["أربع", "خمس", "ست", "سبع"],
        correct_index: 2,
        time_limit_seconds: 30,
        order_index: 2,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "ما هي العملة الرسمية لليابان؟",
        options: ["الوون", "الين", "اليوان", "الروبية"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 3,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "أي متحف يُعد من أكبر وأشهر متاحف العالم ويقع في باريس؟",
        options: ["المتحف البريطاني", "متحف اللوفر", "متحف المتروبوليتان", "متحف الإرميتاج"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 4,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "ما اسم أطول سور بناه الإنسان في التاريخ؟",
        options: ["سور برلين", "سور الصين العظيم", "سور القدس", "سور القسطنطينية"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 5,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "ما هي أقدم حضارة معروفة في التاريخ نشأت في بلاد الرافدين؟",
        options: ["الحضارة الفرعونية", "الحضارة السومرية", "الحضارة الفينيقية", "الحضارة الآشورية"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 6,
        image_url: null,
        question_type: "multi",
      },
      {
        question_text: "ما هو أكثر عنصر كيميائي وفرة في جسم الإنسان من حيث الكتلة؟",
        options: ["الكربون", "الأكسجين", "الهيدروجين", "النيتروجين"],
        correct_index: 1,
        time_limit_seconds: 30,
        order_index: 7,
        image_url: null,
        question_type: "multi",
      },
    ],
  },
];
