/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinRouteImport } from './routes/join'
import { Route as PlayCodeRouteImport } from './routes/play.$code'
import { Route as AuthenticatedHostIndexRouteImport } from './routes/_authenticated/host.index'
import { Route as AuthenticatedHostCodeRouteImport } from './routes/_authenticated/host.$code'
import { Route as AuthenticatedQuizzesIndexRouteImport } from './routes/_authenticated/quizzes.index'
import { Route as AuthenticatedQuizzesQuizIdRouteImport } from './routes/_authenticated/quizzes.$quizId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCodeRoute = PlayCodeRouteImport.update({
  id: '/play/$code',
  path: '/play/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHostIndexRoute = AuthenticatedHostIndexRouteImport.update({
  id: '/_authenticated/host/',
  path: '/host/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHostCodeRoute = AuthenticatedHostCodeRouteImport.update({
  id: '/_authenticated/host/$code',
  path: '/host/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuizzesIndexRoute =
  AuthenticatedQuizzesIndexRouteImport.update({
    id: '/_authenticated/quizzes/',
    path: '/quizzes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedQuizzesQuizIdRoute =
  AuthenticatedQuizzesQuizIdRouteImport.update({
    id: '/_authenticated/quizzes/$quizId',
    path: '/quizzes/$quizId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/play/$code': typeof PlayCodeRoute
  '/host/$code': typeof AuthenticatedHostCodeRoute
  '/quizzes/$quizId': typeof AuthenticatedQuizzesQuizIdRoute
  '/host/': typeof AuthenticatedHostIndexRoute
  '/quizzes/': typeof AuthenticatedQuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/play/$code': typeof PlayCodeRoute
  '/host/$code': typeof AuthenticatedHostCodeRoute
  '/quizzes/$quizId': typeof AuthenticatedQuizzesQuizIdRoute
  '/host': typeof AuthenticatedHostIndexRoute
  '/quizzes': typeof AuthenticatedQuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/play/$code': typeof PlayCodeRoute
  '/_authenticated/host/$code': typeof AuthenticatedHostCodeRoute
  '/_authenticated/quizzes/$quizId': typeof AuthenticatedQuizzesQuizIdRoute
  '/_authenticated/host/': typeof AuthenticatedHostIndexRoute
  '/_authenticated/quizzes/': typeof AuthenticatedQuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/play/$code'
    | '/host/$code'
    | '/quizzes/$quizId'
    | '/host/'
    | '/quizzes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/play/$code'
    | '/host/$code'
    | '/quizzes/$quizId'
    | '/host'
    | '/quizzes'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/play/$code'
    | '/_authenticated/host/$code'
    | '/_authenticated/quizzes/$quizId'
    | '/_authenticated/host/'
    | '/_authenticated/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  PlayCodeRoute: typeof PlayCodeRoute
  AuthenticatedHostCodeRoute: typeof AuthenticatedHostCodeRoute
  AuthenticatedQuizzesQuizIdRoute: typeof AuthenticatedQuizzesQuizIdRoute
  AuthenticatedHostIndexRoute: typeof AuthenticatedHostIndexRoute
  AuthenticatedQuizzesIndexRoute: typeof AuthenticatedQuizzesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$code': {
      id: '/play/$code'
      path: '/play/$code'
      fullPath: '/play/$code'
      preLoaderRoute: typeof PlayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/host/': {
      id: '/_authenticated/host/'
      path: '/host'
      fullPath: '/host/'
      preLoaderRoute: typeof AuthenticatedHostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/host/$code': {
      id: '/_authenticated/host/$code'
      path: '/host/$code'
      fullPath: '/host/$code'
      preLoaderRoute: typeof AuthenticatedHostCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quizzes/': {
      id: '/_authenticated/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof AuthenticatedQuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quizzes/$quizId': {
      id: '/_authenticated/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof AuthenticatedQuizzesQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  PlayCodeRoute: PlayCodeRoute,
  AuthenticatedHostCodeRoute: AuthenticatedHostCodeRoute,
  AuthenticatedQuizzesQuizIdRoute: AuthenticatedQuizzesQuizIdRoute,
  AuthenticatedHostIndexRoute: AuthenticatedHostIndexRoute,
  AuthenticatedQuizzesIndexRoute: AuthenticatedQuizzesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
