/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AuthenticatedCustomChallengeRouteImport } from './routes/_authenticated/custom-challenge'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminImportRouteImport } from './routes/admin/import'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as BrowseIndexRouteImport } from './routes/browse.index'
import { Route as BrowseCategoryRouteImport } from './routes/browse.$category'
import { Route as PlayCodeRouteImport } from './routes/play.$code'
import { Route as AuthenticatedHostIndexRouteImport } from './routes/_authenticated/host.index'
import { Route as AuthenticatedHostCodeRouteImport } from './routes/_authenticated/host.$code'
import { Route as AuthenticatedQuizzesIndexRouteImport } from './routes/_authenticated/quizzes.index'
import { Route as AuthenticatedQuizzesQuizIdRouteImport } from './routes/_authenticated/quizzes.$quizId'
import { Route as AdminQuizzesIndexRouteImport } from './routes/admin/quizzes.index'
import { Route as BrowseQuizIdPreviewRouteImport } from './routes/browse.$quizId.preview'
import { Route as AdminQuizzesQuizIdEditRouteImport } from './routes/admin/quizzes.$quizId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCustomChallengeRoute =
  AuthenticatedCustomChallengeRouteImport.update({
    id: '/custom-challenge',
    path: '/custom-challenge',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseCategoryRoute = BrowseCategoryRouteImport.update({
  id: '/browse/$category',
  path: '/browse/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCodeRoute = PlayCodeRouteImport.update({
  id: '/play/$code',
  path: '/play/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHostIndexRoute = AuthenticatedHostIndexRouteImport.update({
  id: '/host/',
  path: '/host/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHostCodeRoute = AuthenticatedHostCodeRouteImport.update({
  id: '/host/$code',
  path: '/host/$code',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizzesIndexRoute =
  AuthenticatedQuizzesIndexRouteImport.update({
    id: '/quizzes/',
    path: '/quizzes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuizzesQuizIdRoute =
  AuthenticatedQuizzesQuizIdRouteImport.update({
    id: '/quizzes/$quizId',
    path: '/quizzes/$quizId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminQuizzesIndexRoute = AdminQuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BrowseQuizIdPreviewRoute = BrowseQuizIdPreviewRouteImport.update({
  id: '/browse/$quizId/preview',
  path: '/browse/$quizId/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuizzesQuizIdEditRoute = AdminQuizzesQuizIdEditRouteImport.update({
  id: '/quizzes/$quizId/edit',
  path: '/quizzes/$quizId/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/custom-challenge': typeof AuthenticatedCustomChallengeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/users': typeof AdminUsersRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/play/$code': typeof PlayCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/browse/': typeof BrowseIndexRoute
  '/host/$code': typeof AuthenticatedHostCodeRoute
  '/quizzes/$quizId': typeof AuthenticatedQuizzesQuizIdRoute
  '/browse/$quizId/preview': typeof BrowseQuizIdPreviewRoute
  '/host/': typeof AuthenticatedHostIndexRoute
  '/quizzes/': typeof AuthenticatedQuizzesIndexRoute
  '/admin/quizzes/': typeof AdminQuizzesIndexRoute
  '/admin/quizzes/$quizId/edit': typeof AdminQuizzesQuizIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/custom-challenge': typeof AuthenticatedCustomChallengeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/users': typeof AdminUsersRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/play/$code': typeof PlayCodeRoute
  '/admin': typeof AdminIndexRoute
  '/browse': typeof BrowseIndexRoute
  '/host/$code': typeof AuthenticatedHostCodeRoute
  '/quizzes/$quizId': typeof AuthenticatedQuizzesQuizIdRoute
  '/browse/$quizId/preview': typeof BrowseQuizIdPreviewRoute
  '/host': typeof AuthenticatedHostIndexRoute
  '/quizzes': typeof AuthenticatedQuizzesIndexRoute
  '/admin/quizzes': typeof AdminQuizzesIndexRoute
  '/admin/quizzes/$quizId/edit': typeof AdminQuizzesQuizIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/_authenticated/custom-challenge': typeof AuthenticatedCustomChallengeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/users': typeof AdminUsersRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/play/$code': typeof PlayCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/browse/': typeof BrowseIndexRoute
  '/_authenticated/host/$code': typeof AuthenticatedHostCodeRoute
  '/_authenticated/quizzes/$quizId': typeof AuthenticatedQuizzesQuizIdRoute
  '/browse/$quizId/preview': typeof BrowseQuizIdPreviewRoute
  '/_authenticated/host/': typeof AuthenticatedHostIndexRoute
  '/_authenticated/quizzes/': typeof AuthenticatedQuizzesIndexRoute
  '/admin/quizzes/': typeof AdminQuizzesIndexRoute
  '/admin/quizzes/$quizId/edit': typeof AdminQuizzesQuizIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/join'
    | '/custom-challenge'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/import'
    | '/admin/users'
    | '/browse/$category'
    | '/play/$code'
    | '/admin/'
    | '/browse/'
    | '/host/$code'
    | '/quizzes/$quizId'
    | '/browse/$quizId/preview'
    | '/host/'
    | '/quizzes/'
    | '/admin/quizzes/'
    | '/admin/quizzes/$quizId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/join'
    | '/custom-challenge'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/import'
    | '/admin/users'
    | '/browse/$category'
    | '/play/$code'
    | '/admin'
    | '/browse'
    | '/host/$code'
    | '/quizzes/$quizId'
    | '/browse/$quizId/preview'
    | '/host'
    | '/quizzes'
    | '/admin/quizzes'
    | '/admin/quizzes/$quizId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/join'
    | '/_authenticated/custom-challenge'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/import'
    | '/admin/users'
    | '/browse/$category'
    | '/play/$code'
    | '/admin/'
    | '/browse/'
    | '/_authenticated/host/$code'
    | '/_authenticated/quizzes/$quizId'
    | '/browse/$quizId/preview'
    | '/_authenticated/host/'
    | '/_authenticated/quizzes/'
    | '/admin/quizzes/'
    | '/admin/quizzes/$quizId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  JoinRoute: typeof JoinRoute
  BrowseCategoryRoute: typeof BrowseCategoryRoute
  PlayCodeRoute: typeof PlayCodeRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
  BrowseQuizIdPreviewRoute: typeof BrowseQuizIdPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/custom-challenge': {
      id: '/_authenticated/custom-challenge'
      path: '/custom-challenge'
      fullPath: '/custom-challenge'
      preLoaderRoute: typeof AuthenticatedCustomChallengeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/browse/': {
      id: '/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$category': {
      id: '/browse/$category'
      path: '/browse/$category'
      fullPath: '/browse/$category'
      preLoaderRoute: typeof BrowseCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$code': {
      id: '/play/$code'
      path: '/play/$code'
      fullPath: '/play/$code'
      preLoaderRoute: typeof PlayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/host/': {
      id: '/_authenticated/host/'
      path: '/host'
      fullPath: '/host/'
      preLoaderRoute: typeof AuthenticatedHostIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/host/$code': {
      id: '/_authenticated/host/$code'
      path: '/host/$code'
      fullPath: '/host/$code'
      preLoaderRoute: typeof AuthenticatedHostCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quizzes/': {
      id: '/_authenticated/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof AuthenticatedQuizzesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quizzes/$quizId': {
      id: '/_authenticated/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof AuthenticatedQuizzesQuizIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/quizzes/': {
      id: '/admin/quizzes/'
      path: '/quizzes'
      fullPath: '/admin/quizzes/'
      preLoaderRoute: typeof AdminQuizzesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/browse/$quizId/preview': {
      id: '/browse/$quizId/preview'
      path: '/browse/$quizId/preview'
      fullPath: '/browse/$quizId/preview'
      preLoaderRoute: typeof BrowseQuizIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quizzes/$quizId/edit': {
      id: '/admin/quizzes/$quizId/edit'
      path: '/quizzes/$quizId/edit'
      fullPath: '/admin/quizzes/$quizId/edit'
      preLoaderRoute: typeof AdminQuizzesQuizIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCustomChallengeRoute: typeof AuthenticatedCustomChallengeRoute
  AuthenticatedHostCodeRoute: typeof AuthenticatedHostCodeRoute
  AuthenticatedQuizzesQuizIdRoute: typeof AuthenticatedQuizzesQuizIdRoute
  AuthenticatedHostIndexRoute: typeof AuthenticatedHostIndexRoute
  AuthenticatedQuizzesIndexRoute: typeof AuthenticatedQuizzesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCustomChallengeRoute: AuthenticatedCustomChallengeRoute,
  AuthenticatedHostCodeRoute: AuthenticatedHostCodeRoute,
  AuthenticatedQuizzesQuizIdRoute: AuthenticatedQuizzesQuizIdRoute,
  AuthenticatedHostIndexRoute: AuthenticatedHostIndexRoute,
  AuthenticatedQuizzesIndexRoute: AuthenticatedQuizzesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminQuizzesIndexRoute: typeof AdminQuizzesIndexRoute
  AdminQuizzesQuizIdEditRoute: typeof AdminQuizzesQuizIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminImportRoute: AdminImportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminQuizzesIndexRoute: AdminQuizzesIndexRoute,
  AdminQuizzesQuizIdEditRoute: AdminQuizzesQuizIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  JoinRoute: JoinRoute,
  BrowseCategoryRoute: BrowseCategoryRoute,
  PlayCodeRoute: PlayCodeRoute,
  BrowseIndexRoute: BrowseIndexRoute,
  BrowseQuizIdPreviewRoute: BrowseQuizIdPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
